require 'active_reporter/dimension/base'
require 'active_reporter/dimension/bin'
require 'active_reporter/dimension/bin/set'
require 'active_reporter/dimension/bin/table'
require 'active_reporter/dimension/time'
require 'active_reporter/dimension/number'
require 'active_reporter/dimension/category'
require 'active_reporter/dimension/enum'
