require 'active_reporter/serializer/base'
require 'active_reporter/serializer/table'
require 'active_reporter/serializer/csv'
require 'active_reporter/serializer/form_field'
require 'active_reporter/serializer/highcharts'
require 'active_reporter/serializer/hash_table'
require 'active_reporter/serializer/nested_hash'
